-- 코드를 작성해주세요
SELECT COUNT(FISH.FISH_TYPE) AS FISH_COUNT
FROM FISH_INFO AS FISH
INNER JOIN FISH_NAME_INFO AS NAME
ON FISH.FISH_TYPE = NAME.FISH_TYPE
WHERE NAME.FISH_NAME = 'BASS' OR NAME.FISH_NAME = 'SNAPPER'