-- 코드를 입력하세요
SELECT SHIP.FLAVOR
FROM FIRST_HALF AS SHIP
LEFT JOIN ICECREAM_INFO AS INFO
ON SHIP.FLAVOR = INFO.FLAVOR
WHERE INFO.INGREDIENT_TYPE = 'fruit_based' AND SHIP.TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC;